# Generated by Django 5.1.4 on 2024-12-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="full_goal",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="partial_goal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
