# Generated by Django 5.1.4 on 2024-12-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_habit_full_goal_alter_habit_partial_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="full_goal",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habit",
            name="partial_goal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
