# Generated by Django 5.1.4 on 2024-12-21 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_habit_full_goal_alter_habit_partial_goal"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "completed",
                    models.CharField(
                        choices=[("NO", "No"), ("PARTIAL", "Partial"), ("YES", "Yes")],
                        default="NO",
                        max_length=7,
                    ),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="core.habit",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="HabitRecord",
        ),
    ]
