# Generated by Django 5.1.4 on 2024-12-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_habittrack_delete_habitrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habittrack",
            name="completed",
            field=models.IntegerField(choices=[(0, "No"), (1, "Partial"), (2, "Yes")]),
        ),
    ]
