# Generated by Django 5.1.4 on 2024-12-25 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_diarypage_delete_habittrack"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed",
                    models.IntegerField(
                        choices=[(0, "No"), (1, "Partial"), (2, "Yes")]
                    ),
                ),
                (
                    "diary_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_tracks",
                        to="core.diarypage",
                    ),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="core.habit",
                    ),
                ),
            ],
        ),
    ]
