# Generated by Django 5.1.4 on 2024-12-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_habittrack"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habittrack",
            name="habit",
        ),
    ]
