# Generated by Django 5.1.4 on 2024-12-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_habittrack_habit"),
    ]

    operations = [
        migrations.AddField(
            model_name="habittrack",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habittrack",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
