# Generated by Django 5.1.4 on 2024-12-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_habittrack_description_habittrack_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habittrack",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
