# Generated by Django 5.1.4 on 2024-12-25 21:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_habittrack_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diarypage",
            unique_together={("date", "owner")},
        ),
    ]
