# Generated by Django 5.1.4 on 2024-12-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_diarypage_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habittrack",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
