# Generated by Django 5.1.4 on 2024-12-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_habittrack_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habittrack",
            name="diary_page",
        ),
        migrations.DeleteModel(
            name="DiaryPage",
        ),
        migrations.DeleteModel(
            name="HabitTrack",
        ),
    ]
