# Generated by Django 5.1.4 on 2024-12-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_habittrack_diary_page_delete_diarypage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="full_goal",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="partial_goal",
        ),
        migrations.AddField(
            model_name="habit",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="habit",
            name="times_completed",
            field=models.IntegerField(default=0),
        ),
    ]
