# Generated by Django 5.1.4 on 2024-12-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_habit_description_userscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="daily",
                max_length=10,
            ),
        ),
    ]
