# Generated by Django 5.1.4 on 2024-12-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_habit_frequency"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastCleaned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("last_cleaned", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
