# Generated by Django 5.1.4 on 2024-12-29 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_lastcleaned"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LastCleaned",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="frequency",
        ),
        migrations.AddField(
            model_name="userscore",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
